name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Build
        run: bash ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: TheOtherRolesGM.dll
          path: output/TheOtherRolesGM.dll
      
